default_platform(:android)

platform :android do

  desc "Deploy to Play Store"
  lane :deploy do
    upload_to_play_store(
      release_status: 'completed',
      track: 'beta',
      json_key: '../play-store-service-account.json',
      aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab'
    )
  end

end
